export const degreeOptions = [
	"High School",
	"Associate's Degree",
	"Bachelor's Degree",
	"Master's Degree",
	"Engineer's Degree",
	"Diploma",
	"Others",
];

export const courseList = [
	"Computer Science",
	"Electrical Engineering",
	"Mechanical Engineering",
	"Civil Engineering",
	"Chemical Engineering",
	"Biomedical Engineering",
	"Physics",
	"Chemistry",
	"Biology",
	"Mathematics",
	"Environmental Science",
	"Psychology",
	"Economics",
	"Business Administration",
	"Marketing",
	"Finance",
	"Accounting",
	"Political Science",
	"International Relations",
	"Sociology",
	"History",
	"English Literature",
	"Philosophy",
	"Communication Studies",
	"Media Studies",
	"Film Studies",
	"Journalism",
	"Public Relations",
	"Graphic Design",
	"Fine Arts",
	"Music",
	"Theater",
	"Dance",
	"Architecture",
	"Urban Planning",
	"Geography",
	"Anthropology",
	"Criminal Justice",
	"Law",
	"Nursing",
	"Medicine",
	"Dentistry",
	"Pharmacy",
	"Physical Therapy",
	"Occupational Therapy",
	"Nutrition",
	"Sports Science",
	"Exercise Physiology",
	"Kinesiology",
	"Astronomy",
	"Astrophysics",
	"Meteorology",
	"Geology",
	"Oceanography",
	"Robotics",
	"Artificial Intelligence",
	"Machine Learning",
	"Data Science",
	"Cybersecurity",
	"Information Technology",
	"Biotechnology",
	"Genetics",
	"Biochemistry",
	"Microbiology",
	"Pharmacology",
	"Economics",
	"Finance",
	"Marketing",
	"Management",
	"Human Resources",
	"Entrepreneurship",
	"Supply Chain Management",
	"Operations Management",
	"Quantitative Finance",
	"International Business",
	"Real Estate",
	"Healthcare Management",
	"Hospitality Management",
	"Event Management",
	"Tourism",
	"Social Work",
	"Education",
	"Early Childhood Education",
	"Special Education",
	"Counseling Psychology",
	"Clinical Psychology",
	"Forensic Psychology",
	"Industrial-Organizational Psychology",
	"Others",
];
